import { StyleSheet } from "react-native";
import { COLORS, SIZES } from "../../constants/theme";

const styles = StyleSheet.create({
    container:{
        flex:1
    },
    topcontainer:{
        marginTop:100,
        alignItems:"center"
    },
    title:{
        color:COLORS.white,
        fontWeight:"bold",
        fontSize:SIZES.h1*1.5
    },
    subtitle:{
        color:COLORS.white,
        fontSize:SIZES.h3,
        paddingTop:3
    },
    datacontainer:{
        marginTop:30
    },
    inputstyle:{
        color:COLORS.white,
        fontSize:SIZES.h3,
        borderBottomColor:COLORS.lightGrey,
        borderBottomWidth:1,
        paddingVertical:15,
        marginHorizontal:15,
        marginVertical:2
    },
    btncontainer:{
        marginTop:10
    },
    button1:{
        backgroundColor:COLORS.primary,
        padding:20,
        borderRadius:10,
        marginHorizontal:30,
        justifyContent:"center",
        marginVertical:5,
        alignItems:"center"
    },
    btntext:{
        color:COLORS.white,
        fontWeight:"bold",
        fontSize:SIZES.h4
    },
    button2:{
        flexDirection:"row",
        backgroundColor:COLORS.blue,
        padding:15,
        borderRadius:10,
        marginHorizontal:30,
        justifyContent:"center",
        marginVertical:10,
        alignItems:"center"
    },
    logo:{
        marginRight:10
    },
    text:{
        color:COLORS.white,
        textAlign:"center",
        fontWeight:"600",
        fontSize:SIZES.h5,
        marginTop:10
    },
    bottomcontainer:{
        justifyContent:"center",
        marginTop:5
    },
    radiologiccontainer:{
        backgroundColor:COLORS.blue,
        borderRadius:10,
        marginHorizontal:30,
        marginTop:50,
    },
    radiostat:{
        color:COLORS.white,
        textAlign:"center",
        fontWeight:"600",
        fontSize:SIZES.h4,
        marginTop:5,
        opacity:0.5,
        textTransform:"uppercase",
        letterSpacing:2
    },
    radiocontainer:{
        flexDirection:"row",
        justifyContent:"space-evenly",
        alignItems:"center"
    },
    radiocircle:{
        width:20,
        height:20,
        marginRight:10,
        borderColor:COLORS.white,
        borderRadius:10,
        borderWidth:2
    },
    radiobg:{
        width:10,
        height:10,
        margin:3,
        backgroundColor:COLORS.white,
        borderRadius:5
    },
    radiotext:{
        color:COLORS.white,
        paddingBottom:10,
        fontWeight:"600",
        fontSize:SIZES.h5,
        marginTop:10
    },
    radiotextcontainer:{
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center"
    },
    radioerrorstyle:{
        color:COLORS.primary,
        marginLeft:15,
        fontWeight:"600",
        fontSize:SIZES.h4,
        marginTop:20,
        textAlign:"center"
    },
    errorstyle:{
        color:COLORS.primary,
        marginLeft:15,
        fontWeight:"600",
        fontSize:SIZES.h4
    }
    
})

export default styles;